version: '3.5'

services:

  localstack:
    image: localstack/localstack:1.3.1
    environment:
      - AWS_DEFAULT_REGION=us-east-1
      - EDGE_PORT=4566
      - SERVICES=sns
    ports:
      - '4566:4566'
      - '${PORT_WEB_UI-8089}:${PORT_WEB_UI-8080}'
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./docker/localstack/volume}:/var/lib/localstack"
      - "${LOCALSTACK_VOLUME_DIR:-./docker/localstack/docker}:/var/run/docker.sock"
